# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pull Request

on:
  pull_request:
    branches: [ "main" ]
permissions: write-all
jobs:
  build:

    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count
    - name: Test with pytest
      run: |
        python -m pytest